"""empty message

Revision ID: 370a9f0c05f8
Revises: b19457d4e7b5
Create Date: 2016-07-04 01:37:23.086146

"""

# revision identifiers, used by Alembic.
revision = '370a9f0c05f8'
down_revision = 'b19457d4e7b5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlmodels', sa.Column('private', sa.Boolean(), nullable=False))
    op.drop_column('mlmodels', 'status')
    op.add_column('modeltests', sa.Column('private', sa.Boolean(), nullable=False))
    op.drop_column('modeltests', 'visibility')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modeltests', sa.Column('visibility', postgresql.ENUM(u'private', u'public', u'deleted', name='status_types'), autoincrement=False, nullable=False))
    op.drop_column('modeltests', 'private')
    op.add_column('mlmodels', sa.Column('status', postgresql.ENUM(u'private', u'public', u'deleted', name='status_types'), autoincrement=False, nullable=False))
    op.drop_column('mlmodels', 'private')
    ### end Alembic commands ###
