"""empty message

Revision ID: 752b6ec66598
Revises: 370a9f0c05f8
Create Date: 2017-03-20 18:47:17.133722

"""

# revision identifiers, used by Alembic.
revision = '752b6ec66598'
down_revision = '370a9f0c05f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'refresh_token')
    ### end Alembic commands ###
