"""empty message

Revision ID: fcb40ad93b2e
Revises: fbfd97ce1e35
Create Date: 2016-01-10 18:21:56.074825

"""

# revision identifiers, used by Alembic.
revision = 'fcb40ad93b2e'
down_revision = 'fbfd97ce1e35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
