export const SHOW_SELECT_IMAGES_MODAL = 'SHOW_SELECT_IMAGES_MODAL';
export const HIDE_SELECT_IMAGES_MODAL = 'HIDE_SELECT_IMAGES_MODAL';
export const TOGGLE_IMAGE = 'TOGGLE_IMAGE';
export const TOGGLE_ALL_IMAGES = 'TOGGLE_ALL_IMAGES';
