"""empty message

Revision ID: 23b84aaeccac
Revises: fcb40ad93b2e
Create Date: 2016-01-10 18:25:48.476992

"""

# revision identifiers, used by Alembic.
revision = '23b84aaeccac'
down_revision = 'fcb40ad93b2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('connections', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'updated')
    op.drop_column('connections', 'created')
    ### end Alembic commands ###
