"""empty message

Revision ID: 76c600a21fcb
Revises: 23b84aaeccac
Create Date: 2016-02-17 02:55:47.676581

"""

# revision identifiers, used by Alembic.
revision = '76c600a21fcb'
down_revision = '23b84aaeccac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlmodels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('modeltests', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modeltests', 'description')
    op.drop_column('mlmodels', 'description')
    ### end Alembic commands ###
